---
# TODO: Collect repeated variables into a single place

- name: "Set up XNAT users and their projects"
  ansible.builtin.include_tasks: setup_single_testuser.yml
  loop: "{{ range(1, n_users + 1) | list }}"
  loop_control:
    loop_var: user_id
