---
- name: Install lxml using pip
  ansible.builtin.pip:
    name:
      - lxml

- name: Ensure dependencies are installed
  ansible.builtin.yum:
    name: ["postgresql{{ postgresql_version }}", "wget"]
    state: installed

- name: "Configure XNAT directories"
  import_tasks: directories.yml

- name: "Add or upgrade XNAT code"
  import_tasks: upgrade_xnat.yml

- name: "Add or upgrade plugins"
  import_tasks: plugins.yml

- name: "Add or upgrade pipeline installer"
  import_tasks: pipelines.yml
  when: pipeline_engine_enabled

- name: "Configure XNAT settings files"
  import_tasks: settings_files.yml

- name: "Configure LDAP for XNAT"
  import_tasks: ldap.yml
  when: ldap.enabled

- name: "XNAT site configuration"
  import_tasks: configure.yml
