---
- name: Install lxml using pip
  ansible.builtin.pip:
    name:
      - lxml
  when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "8"

- name: Ensure dependencies are installed
  ansible.builtin.yum:
    name: ["postgresql{{ postgresql_version }}", "wget"]
    state: installed

- name: "Configure XNAT directories"
  include: directories.yml

- name: "Add or upgrade XNAT code"
  include: upgrade_xnat.yml

- name: "Add or upgrade plugins"
  include: plugins.yml

- name: "Add or upgrade pipeline installer"
  include: pipelines.yml
  when: pipeline_engine_enabled

- name: "Configure XNAT settings files"
  include: settings_files.yml

- name: "Configure LDAP for XNAT"
  include: ldap.yml
  when: ldap.enabled

- name: "XNAT site configuration"
  include: configure.yml
