---
# If user is not found (404 or 500) then the user does not yet exist
- name: "Check existence of user"
  ansible.builtin.uri:
    url: "{{ xnat_web_server.url }}/xapi/users/profX"
    user: "{{ xnat_service_admin.username }}"
    password: "{{ xnat_service_admin.password }}"
    method: GET
    validate_certs: "{{ ssl.validate_certs }}"
    status_code: 200, 404, 500
  register: service_admin_check

- name: "Create project user"
  ansible.builtin.uri:
    url: "{{ xnat_web_server.url }}/xapi/users/"
    user: "{{ xnat_service_admin.username }}"
    password: "{{ xnat_service_admin.password }}"
    method: POST
    body_format: json
    body:
      admin: true
      username: "profX"
      password: "carlos1602"
      firstName: "Charles"
      lastName: "Xavier"
      email: "c.xavier@{{ hostvars['xnat_web']['ansible_host'] }}"
      verified: true
      enabled: true
    validate_certs: "{{ ssl.validate_certs }}"
    status_code: 201
  when: service_admin_check.status in [404, 500]

# Create a project owned by the user
