---
# Variables for the Container Service hosts and the clients (web servers) it serves
xnat_container_service:
  name: "Container Service"
  host: "{{ hostvars['xnat_cserv']['ansible_host'] }}"
  ip: "{{ hostvars['xnat_cserv']['private_ip'] }}"
  port: "2376"
  clients:
    - "{{ hostvars['xnat_web']['ansible_host'] }}"
  client_ips:
    - "{{ hostvars['xnat_web']['ansible_ip'] }}"

xnat_container_service_temp_files_cert_dir: "{{ ansible_cache_dir }}/cserv_certificates/cserv"
