---
- name: Install container service client
  hosts: web
  become: true
  become_user: root
  become_method: sudo
  gather_facts: true

  roles:
    - { role: container_service_client, when: container_service_enabled }
