---
- name: Install dependencies
  hosts: web
  become: true
  become_user: root
  become_method: sudo
  gather_facts: true

  roles:
    - { role: provision }
    - { role: mirsg.install_python }
    - { role: java }
    - { role: tomcat }
    - { role: nginx }

- name: Install and configure XNAT
  hosts: web
  become: true
  become_user: root
  become_method: sudo
  gather_facts: true

  roles:
    - { role: xnat }
    - { role: container_service_client, when: container_service_enabled }
