---
- name: Install and configure XNAT
  hosts: xnat
  become: true
  gather_facts: true

  roles:
    - role: wait_until_running
    - role: mount_efs
    - role: mirsg.infrastructure.provision
    - role: mirsg.infrastructure.install_python
    - role: mirsg.infrastructure.install_java
    - role: mirsg.infrastructure.tomcat
    - role: mirsg.infrastructure.nginx
    - role: mirsg.infrastructure.xnat

- name: Setup Container Service on hosts
  hosts: container_service_host
  become: true
  gather_facts: true

  roles:
    - role: wait_until_running
    - role: mount_efs
    - role: mirsg.infrastructure.provision
    - role: mirsg.infrastructure.install_python
    - role: mirsg.infrastructure.docker
    - role: configure_docker_swarm

- name: Setup Container Service on clients (i.e. the web servers)
  hosts: container_service_client
  become: true
  gather_facts: true

  roles:
    - role: mirsg.infrastructure.xnat_container_service
    - role: container_service_images
