---
# Set up the Container Service on the hosts
# The client configuration is done in `install_xnat.yml`
- name: Wait until instance is running
  hosts: cserv_hosts
  gather_facts: false

  roles:
    - { role: wait_until_running }

- name: Provision container service host
  hosts: cserv_hosts
  become: true
  become_user: root
  become_method: sudo
  gather_facts: true

  roles:
    - { role: provision }
    - { role: mirsg.install_python }
    - { role: docker }
    - {
      role: sign_docker_client_cert,
      clients: "{{ xnat_container_service.clients }}",
    }
