---
ansible_cache_dir: "{{ lookup('env', 'HOME') }}/ansible_persistent_files"

# mirsg.infrastructure.postgresql - download and install - we need to do this on both the web server and the db
postgresql_install:
  disable_gpg_check: false
  rpm: >-
    https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{
    ansible_facts['distribution_major_version'] }}-{{
    ansible_facts['architecture'] }}/pgdg-redhat-repo-latest.noarch.rpm
  yum_package: postgresql{{ postgresql_version }}-server
  yum_contrib_package: postgresql{{ postgresql_version }}-contrib # required only on CentOS 7
  yum_client_package: postgresql{{ postgresql_version }}
