---
- name: Ensure the download directory  exists
  ansible.builtin.file:
    path: "{{ xnat_project_data.file | dirname }}"
    state: directory
    mode: "0755"

- name: Download the data if we do not have it or if it has changed
  amazon.aws.s3_object:
    bucket: "{{ xnat_project_data.s3_bucket }}"
    object: "{{ xnat_project_data.s3_object }}"
    dest: "{{ xnat_project_data.file }}"
    mode: get
    overwrite: different
  register: data_downloaded

- name: Check if project data directory exists
  ansible.builtin.stat:
    path: "{{ xnat_project_data.directory }}"
  register: xnat_project_data_directory

- name: Unzip the data if necessary
  when: not xnat_project_data_directory.stat.exists or data_downloaded.changed
  block:

    - name: Ensure the data directory exists
      ansible.builtin.file:
        path: "{{ xnat_project_data.directory }}"
        state: directory
        mode: "0755"

    - name: Unarchive the project data
      ansible.builtin.unarchive:
        src: "{{ xnat_project_data.file }}"
        dest: "{{ xnat_project_data.directory }}"
        mode: "0644"
