---
# Ensure we have project data to upload
- name: Check if project data exists locally
  ansible.builtin.stat:
    path: "{{ xnat_project_data.file }}"
  register: xnat_project_data_file

- name: Download the data if we do not already have it
  ansible.builtin.get_url:
    url: "{{ xnat_project_data.url }}"
    dest: "{{ xnat_project_data.file }}"
    mode: "0644"
  when: not xnat_project_data_file.stat.exists

- name: Check if project data directory exists
  ansible.builtin.stat:
    path: "{{ xnat_project_data.directory }}"
  register: xnat_project_data_directory

- name: Unzip the data if necessary
  when: not xnat_project_data_directory.stat.exists
  block:

    - name: Create the data directory
      ansible.builtin.file:
        path: "{{ xnat_project_data.directory }}"
        state: directory
        mode: "0755"

    - name: Unarchive the project data
      ansible.builtin.unarchive:
        src: "{{ xnat_project_data.file }}"
        dest: "{{ xnat_project_data.directory }}"
        mode: "0644"
