---
- name: Ensure the download directory  exists
  ansible.builtin.file:
    path: "{{ xnat_download_dir }}"
    state: directory
    mode: "0755"

- name: Download the data if we do not have it or if it has changed
  ansible.builtin.get_url:
    url: "{{ xnat_project_data.url }}"
    dest: "{{ xnat_project_data.zip_file }}"
    mode: "0644"
  register: data_downloaded

- name: Check if project data directory exists
  ansible.builtin.stat:
    path: "{{ xnat_project_data.unzip_target }}"
  register: xnat_project_data_directory

- name: Unzip the data if necessary
  when: not xnat_project_data_directory.stat.exists or data_downloaded.changed
  block:

    - name: Ensure the data directory exists
      ansible.builtin.file:
        path: "{{ xnat_project_data.unzip_target }}"
        state: directory
        mode: "0755"

    - name: Unarchive the project data
      ansible.builtin.unarchive:
        src: "{{ xnat_project_data.zip_file }}"
        dest: "{{ xnat_project_data.unzip_target }}"
        mode: "0644"
        remote_src: true
