---
- name: "Create investigator if they do not already exist"
  ansible.builtin.include_tasks: create_investigator.yml

- name: "Create project if it does not already exist"
  ansible.builtin.include_tasks: create_project.yml

- name: "Create project owner if they do not already exist"
  ansible.builtin.include_tasks: create_owner.yml

- name: "Download project data if we do not have a local copy"
  ansible.builtin.include_tasks: download_data.yml

- name: "Upload data to XNAT"
  ansible.builtin.include_tasks: upload_data.yml
