---
- name: Check if SELinux is in 'enforcing' mode
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: "^SELINUX=enforcing"
    state: absent
  check_mode: true
  changed_when: false
  register: selinux_enforced

- name: Check SELinux flag on but VM off
  ansible.builtin.fail:
    msg: "SELinux flag enabled but disabled on VM"
  when: selinux_enabled and not selinux_enforced.found

- name: Check SELinux flag off but VM on
  ansible.builtin.fail:
    msg: "SELinux flag disabled but enabled on VM"
  when: not selinux_enabled and selinux_enforced.found

- name: Configure SELinux to allow nginx to listen on port {{ dicom_port }}
  community.general.seport:
    ports: "{{ dicom_port }}"
    proto: tcp
    setype: http_port_t
    state: present
  when: selinux_enabled

- name: Ensure nginx is installed
  ansible.builtin.yum:
    name: ["nginx", "nginx-mod-stream"]
    state: installed

- name: Ensure nginx certs directory exists
  ansible.builtin.file:
    path: "{{ nginx.certs_dir }}"
    owner: "{{ nginx.owner }}"
    group: "{{ nginx.group }}"
    state: directory
    mode: 0700

- name: Copy server certificates to nginx
  ansible.builtin.copy:
    remote_src: true
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ nginx.owner }}"
    group: "{{ nginx.group }}"
    mode: 0600
  with_items:
    - { src: "{{ ssl.server_cert }}", dest: "{{ nginx.ssl_cert_file }}" }
    - { src: "{{ ssl.server_key }}", dest: "{{ nginx.ssl_key_file }}" }
  notify: Reload nginx
  when: ssl.use_ssl

- name: Generate Diffie-Hellman (DH) parameters with {{ diffie_helman_size_bits }} bits.
  community.crypto.openssl_dhparam:
    path: "{{ nginx.dh_params_file }}"
    size: "{{ diffie_helman_size_bits }}"
    select_crypto_backend: "openssl"
  notify: Reload nginx

- name: Copy nginx config file
  ansible.builtin.template:
    src: "nginx.j2"
    dest: "{{ nginx.conf_file }}"
    owner: "{{ nginx.owner }}"
    group: "{{ nginx.group }}"
    mode: 0644
    force: true
  notify: Reload nginx

- name: Ensure nginx is running
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
