---
xnat_container_service:
  name: "container service"
  host: "{{ hostvars['xnat_cserv']['ansible_host'] }}"
  ip: "{{ hostvars['xnat_cserv']['ansible_ip'] }}"
  port: "2376"
  clients:
    - "{{ hostvars['xnat_web']['ansible_host'] }}"
  client_ips:
    - "{{ hostvars['xnat_web']['ansible_ip'] }}"

xnat_container_service_temp_files_cert_dir: "{{ ansible_cache_dir }}/cserv_certificates/cserv"
