---
# web server VM
xnat_web_server:
  host: "{{ hostvars['xnat_web']['ansible_host'] }}"
  url: "http://{{ hostvars['xnat_web']['ansible_host'] }}"
  ip: "{{ hostvars['xnat_web']['private_ip'] }}"
  storage_dir: "{{ EXTERNAL_STORAGE_DRIVE }}/data"

# database server VM
xnat_db:
  host: "{{ hostvars['xnat_db']['ansible_host'] }}"
  port: 5432
  listen_addresses: "*"
  postgres_xnat_database: "xnat"
  postgres_xnat_user: "xnat"
  postgres_xnat_password: "{{ vault_postgres_xnat_password }}"
  storage_dir: "{{ EXTERNAL_STORAGE_DRIVE }}/pgsql"
  data_dir: "{{ EXTERNAL_STORAGE_DRIVE }}/pgsql/{{ postgresql_version }}/data"
  backups_dir: "{{ EXTERNAL_STORAGE_DRIVE }}/pgsql/backups"
