---
# web server VM
web_server:
  host: "{{ hostvars['xnat_web']['ansible_host'] }}"
  url: "http://{{ hostvars['xnat_web']['ansible_host'] }}"
  ip: "{{ hostvars['xnat_web']['private_ip'] }}"
  storage_dir: "{{ external_storage_drive }}/data"

# database server VM
db_server:
  host: "{{ hostvars['xnat_web']['database_hostname'] }}"
  port: "{{ hostvars['xnat_web']['database_port'] }}"
  postgres_xnat_database: "{{ hostvars['xnat_web']['database_name'] }}"
  postgres_xnat_user: "{{ hostvars['xnat_web']['database_user'] }}"
  postgres_xnat_password: "{{ vault_postgres_xnat_password }}"
