---
- name: Install nginx
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Install nginx
      ansible.builtin.yum:
        name: nginx
        state: present

    - name: Add index page
      ansible.builtin.template:
        src: index.html
        dest: /usr/share/nginx/html
        mode: "755"

    - name: Start nginx
      ansible.builtin.service:
        name: nginx
        state: started
