---
all:
  # List of all servers, defining their alias and IP (ansible_host)
  hosts:
    xnat_web:
      ansible_host: ec2-18-170-222-160.eu-west-2.compute.amazonaws.com
      ansible_ip: 18.170.222.160
      ansible_port: 22
    xnat_db:
      ansible_host: ec2-3-10-180-192.eu-west-2.compute.amazonaws.com
      ansible_ip: 3.10.180.192
      ansible_port: 22
