---
# Support for ipv6
ipv6_enabled: false

# Bit size for OpenSSL Diffie-Hellman Parameters. Higher bit sizes are more
# secure, but require exponentially larger times for the one-off parameter
# generation. Use 4096 for production. These may take 10mins+ to generate but
# are only generated once per server.
# For local testing (non-production), use 2096 to speed up deployment.
diffie_helman_size_bits: 2048

dicom_port: 8104
xnat_dicom_port: 8105
