---
# XNAT supports PostgreSQL 10 - 14
# See: https://groups.google.com/g/xnat_discussion/c/INKizGBktEQ/m/jauYgo8oAAAJ
postgresql_version: "14"

# mirsg.postgresql - download and install - we need to do this on both the web server and the db
postgresql_install:
  disable_gpg_check: false
  rpm: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_facts['distribution_major_version'] }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
  yum_package: "postgresql{{ postgresql_version }}-server"
  yum_contrib_package: "postgresql{{ postgresql_version }}-contrib"
