---
tomcat_version: 9.0.76

tomcat_webapp_name: "ROOT"

tomcat:
  catalina_home: "/usr/share/tomcat"
  config_file: "/usr/share/tomcat/conf/tomcat.conf"
  server_config_file: "/usr/share/tomcat/conf/server.xml"
  service_config_file: "/etc/systemd/system/tomcat.service"
  owner: "tomcat"
  group: "tomcat"
  hostname: localhost
  server_port: 8005
  catalina_port: 8983
  catalina_redirect_port: 8443
  shutdown_port: 8005
  port: 8080
  root: "/usr/share/tomcat/webapps/{{ tomcat_webapp_name }}"
  root_webapp: "/usr/share/tomcat/webapps/{{ tomcat_webapp_name }}.war"
  binary_url: "https://archive.apache.org/dist/tomcat/tomcat-\
    {{ tomcat_version.split('.')[0] }}/v{{ tomcat_version }}/bin/\
    apache-tomcat-{{ tomcat_version }}.tar.gz"

# You may want to increase the heap space if you have enough RAM available
java_mem:
  Xms: "512M"
  Xmx: "1G"
  MetaspaceSize: "300M"
