---
xnat_plugin_urls:
  - "https://api.bitbucket.org/2.0/repositories/xnatdev/xsync/downloads/xsync-plugin-all-1.5.0.jar"
  #- "https://api.bitbucket.org/2.0/repositories/xnatx/ldap-auth-plugin/downloads/ldap-auth-plugin-1.1.0.jar"
  - "https://api.bitbucket.org/2.0/repositories/xnatdev/container-service/downloads/container-service-3.3.0-fat.jar"
  - "https://api.bitbucket.org/2.0/repositories/xnatx/xnatx-batch-launch-plugin/downloads/batch-launch-0.6.0.jar"
  - "https://github.com/VUIIS/dax/raw/main/misc/xnat-plugins/dax-plugin-genProcData-1.4.2.jar"
  - "https://api.bitbucket.org/2.0/repositories/icrimaginginformatics/ohif-viewer-xnat-plugin/downloads/ohif-viewer-3.4.1.jar"
  - "https://api.bitbucket.org/2.0/repositories/xnatx/ml-plugin/downloads/ml-plugin-1.0.2.jar"
  - "https://api.bitbucket.org/2.0/repositories/xnatx/datasets-plugin/downloads/datasets-plugin-1.0.2.jar"
  - "https://api.bitbucket.org/2.0/repositories/xnatdev/xnat-image-viewer-plugin/downloads/ximgview-plugin-1.0.2.jar"
  - "https://api.bitbucket.org/2.0/repositories/xnatx/xnatx-dxm-settings-plugin/downloads/dxm-settings-plugin-1.0.jar"

xnat_plugin_bundle_urls: []
xnat_plugin_packages: []
xnat_server_specific_plugin_urls: []
xnat_server_specific_plugin_packages: []

pipeline_engine_enabled: false

java_keystore:
  keystore_pass: "{{ vault_keystore_password }}"

# JSON representation of the site-wide anonymisation script: this could be
# defined in a string, or extracted from a template file e.g. using
# lookup('template, 'foo.j2') | to_json
xnat_sitewide_anonymization_script: "{{ xnat_common_config.sitewideAnonymizationScript | to_json }}"

# Path to server logo file
xnat_config_logo: "/images/logo.png"

xnat_service_admin:
  username: "admin_user"
  firstname: "admin"
  lastname: "user"
  password: "{{ vault_service_admin_password }}"

# XNAT configuration shared between all servers
xnat_common_config:
  admin_email: "xnatadmin@{{ hostvars['xnat_web']['ansible_host'] }}"
  restrictUserListAccessToAdmins: true
  uiAllowNonAdminProjectCreation: false
  allowNonAdminsToClaimUnassignedSessions: true
  reloadPrearcDatabaseOnStartup: true
  par: false
  primaryAdminUsername: "{{ xnat_service_admin.username }}"
  receivedFileUser: "{{ xnat_service_admin.username }}"
  ipsThatCanSendEmailsThroughRest: "127.0.0.1"
  sessionXmlRebuilderInterval: "5"
  # "^.*$" for all IPs
  enabledProviders: ["localdb"]
  enableSitewideAnonymizationScript: true
  sitewideAnonymizationScript: "//\nversion \"6.1\"\nproject != \"Unassigned\" ? (0008,1030) := project\n(0010,0010) := subject\n(0010,0020) := session"

# XNAT configuration
xnat_config:
  site_name: "XNAT"
  site_description: "<h1>XNAT</h1><p>An instance of XNAT deployed on AWS."
  admin_password: "{{ vault_admin_password }}"

# LDAP configuration
ldap:
  enabled: false
  name: ""
  address: ""
  userdn: ""
  password: "{{ vault_ldap_password }}"
  base: ""
  filter: ""
  ca_cert: ""
  keystore_alias: ""

# Mail server settings
smtp:
  enabled: "false"
  hostname: "192.168.56.101"
  port: "2525"
  protocol: "smtp"
  auth: ""
  username: ""
  password: "{{ vault_smtp_password }}"
  start_tls: "false"
  ssl_trust: "*"
