---
- name: Install locale language pack
  ansible.builtin.yum:
    name: glibc-langpack-en
    state: present

- name: Set locale # noqa: no-changed when
  ansible.builtin.command: "localectl set-locale LANGUAGE={{ server_locale | quote }}"
  register: set_locale
  failed_when: "'Failed to issue method call: ' in set_locale.stderr"
 