---
- name: Ensure nfs-common is installed (for mounting EFS volume)
  ansible.builtin.yum:
    name: nfs-utils
    state: present

- name: Ensure mount directory exists
  ansible.builtin.file:
    path: "{{ efs_mount.directory }}"
    state: directory
    mode: "0755"

- name: Mount the volume
  ansible.posix.mount:
    src: "{{ efs_mount.src }}"
    name: "{{ efs_mount.directory }}"
    fstype: "{{ efs_mount.fstype }}"
    opts: "{{ efs_mount.opts }}"
    state: "{{ efs_mount.state }}"
