---
- name: Ensure epel is installed
  become: true
  ansible.builtin.yum:
    name: "epel-release"
    state: installed

- name: Disable default Postgres module (Red Hat 8+) # noqa command-instead-of-module
  ansible.builtin.command: yum module disable -y postgresql
  register: disable_postgresql_module
  changed_when:
    - "'Disabling modules:' in disable_postgresql_module.stdout"
