---
- name: Ensure base mirrorlist is in repository file (CentOS)
  community.general.ini_file:
    path: /etc/yum.repos.d/CentOS-Base.repo
    section: base
    option: mirrorlist
    value: http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os
    backup: true
    mode: 0644
  when: ansible_facts['distribution'] == "CentOS"

- name: Ensure updates mirrorlist is in repository file (CentOS)
  community.general.ini_file:
    path: /etc/yum.repos.d/CentOS-Base.repo
    section: updates
    option: mirrorlist
    value: http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=updates
    backup: true
    mode: 0644
  when: ansible_facts['distribution'] == "CentOS"

- name: upgrade all packages # noqa package-latest
  ansible.builtin.yum:
    name: "*"
    state: latest

- name: Ensure epel is installed
  become: true
  ansible.builtin.yum:
    name: "epel-release"
    state: installed
