---
name: links

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  links:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check links
        uses: UCL-MIRSG/.github/actions/links@ee53b1a497918d8f7c5cc4051c71b3e27ce15b7f # v0
        with:
          app-id: ${{ vars.LINKS_APP_ID }}
          app-pem: ${{ secrets.LINKS_PRIVATE_KEY }} # zizmor: ignore[secrets-outside-env]
