---
name: Manage issues on the projects board

on:
  issues:
    types:
      - opened

jobs:
  add-issue-to-project:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: UCL-MIRSG/.github/actions/add-to-project@fa217391231c656a9a110d6bd82956b8274b551c # v0
        with:
          app-id: ${{ secrets.APP_ID }} # zizmor: ignore[secrets-outside-env]
          app-pem: ${{ secrets.APP_PEM }} # zizmor: ignore[secrets-outside-env]
