---
name: Update the terraform lock file to work on both platforms

on:
  pull_request:

jobs:
  terraform-lock-update:
    runs-on: ubuntu-slim
    steps:
      - uses: UCL-MIRSG/.github/actions/terraform-lock-update@f0317ea26124fe0b3b923d881ac956301a11ea56 # v0
        with:
          app-id: ${{ vars.TERRAFORM_LOCK_UPDATE_APP_ID }}
          app-pem: ${{ secrets.TERRAFORM_LOCK_UPDATE_APP_PRIVATE_KEY }}
