---
name: Update the terraform lock file to work on both platforms

on:
  pull_request:

jobs:
  terraform-lock-update:
    runs-on: ubuntu-slim
    steps:
      - uses: UCL-MIRSG/.github/actions/terraform-lock-update@7aa09ca857cfec628f3f296bc3e3903d9c3a248f # v0
        with:
          app-id: ${{ vars.TERRAFORM_LOCK_UPDATE_APP_ID }}
          app-pem: ${{ secrets.TERRAFORM_LOCK_UPDATE_APP_PRIVATE_KEY }}
