---
name: Generate terraform docs
on:
  - pull_request

jobs:
  docs:
    runs-on: ubuntu-slim
    steps:
      - uses: UCL-MIRSG/.github/actions/terraform-docs@v0.235.0
        with:
          app-id: ${{ vars.TERRAFORM_DOCS_APP_ID }}
          app-pem: ${{ secrets.TERRAFORM_DOCS_APP_PRIVATE_KEY }}
          working-dir: ./provision
